project:
  type: website
  resources:
    - assets/scratch-*.ipynb
    - assets/*.csv
    - assets/*json
  render:
    - "*.qmd"
    - "!assets/*ipynb"

website:
  title: "IST 356 Spring 2026"
  image: "/images/ischool_logo_reverseX2.png"
  open-graph: true
  twitter-card: true
  site-url: enter_gitHub_pages_URL_here
  repo-url: enter_github_repo_URL_here
  page-navigation: true
  navbar:
    border: true
    foreground: "#F76900"
    background: "#000E54"
    collapse: false
    right:
      - text: "<img src='/images/ischool_logo_reverseX2.png' height='30'>"
        href: https://ischool.syracuse.edu
        aria-label: "iSchool homepage"
        target: _blank
  sidebar:
    #logo: "/images/ischool_logo_reverseX2.png"
    align: center
    border: true
    foreground: "#F76900"
    background: "#000E54"
    title: false
    pinned: true
    style: "docked"
    collapse-level: 1
    contents: auto
  page-footer:
    border: true
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "Adapted from the [Syracuse University Open Source Program Office's](https://opensource.syracuse.edu/) [workshop template](https://github.com/SU-OSPO/workshop-template)."
    foreground: "#F76900"
    background: "#000E54"

format:
  html:
    theme:
      - lumen
      - fonts.scss
    toc: true
    mainfont: ShermanSans, Verdana, sans-serif

callout-appearance: default

execute:
  freeze: auto



